name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build for macOS
      run: swift build -v
    - name: Run tests for macOS
      run: swift test -v
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MobilePassiveData-Package -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
    - name: Run tests for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MobilePassiveData-Package -destination "platform=iOS Simulator,OS=15.2,name=iPhone 12" | xcpretty
